set shell := ["bash", "-cu"]

PYTHON_VERSION := "3.14"
VENV_DIR := ".venv"

default:
    @just --list

setup:
    #!/usr/bin/env bash
    rm -rf {{ VENV_DIR }}
    curl -LsSf https://astral.sh/uv/0.9.1/install.sh | sh
    uv venv {{ VENV_DIR }} --python {{ PYTHON_VERSION }}
    PARENT_DIR=$(pwd)
    echo "export PYTHONPATH=$PARENT_DIR/" >> .venv/bin/activate
    source .venv/bin/activate && uv pip install .
    echo Activate the virtual environment:
    echo "Run: source {{ VENV_DIR }}/bin/activate"
